<?php require 'includes/common.php'; ?>
<!DOCTYPE>
<html>
<head>
  <title>Terms of Service | Selectiall Services</title>
  <?php include 'includes/additional.php' ?>
</head>

<body>
<?php include 'includes/header.php' ?>
<div class="jumbotron text-center" style="margin-top: 140px;"><h2>Terms Of Service</h2></div>
<div class="container" style="margin-top: 50px;">
  <h3><b>Welcome to Selectiall!</b></h3>
  <p>Thanks for using our products and services (“Services”). The Services are provided by Onicorn Selectiall Services Pvt Limited (“Selectiall”), located at 439, Mahaveer Lane, Garrage Chhak, Old Town, Bhubaneswar.<br><br>
 By using our Services, you are agreeing to these terms. Please read them carefully.<br><br>
 Our Services are very diverse, so sometimes additional terms or product requirements may apply. Additional terms will be available with the relevant Services, and those additional terms become part of your agreement with us if you use those Services.</p><br>

  <h4><b>A. Acceptance of Terms</b></h4>
  <p>PLEASE READ THE TERMS OF USE THOROUGHLY AND CAREFULLY. The terms and conditions set forth below (“Terms of Use”) and the Privacy Policy (as defined below) constitute a legally-binding agreement between Selectiall operating from its Gurgaon Corporate Office and you. These Terms of Use contain provisions that define your limits, legal rights and obligations with respect to your use of and participation in:
    <ol type="i">
      <li> the Selectiall website and mobile application, including the classified advertisements, forums, various email functions and Internet links, and all content and Selectiall services available through the domain and sub-domains of Selectiall located at www.Selectiall.com (collectively referred to herein as the “Website”) </li>
      <li> the online transactions between those users of the Website who are offering services (each, a “Service Professional”) and those users of the Website who are obtaining services (each, a “Service User”) through the Website (such services, collectively, the “Services”). The Terms of Use described below incorporate the Privacy Policy and apply to all users of the Website, including users who are also contributors of video content, information, private and public messages, advertisements, and other materials or Services on the Website.</li>
    </ol></p>
    <p>The Website is owned and operated by Onicorn Selectiall Services Pvt. Ltd.<br>
  You acknowledge that the Website serves as a venue for the online distribution and publication of user submitted information between Service Professionals and Service Users, and, by using, visiting, registering for, and/or otherwise participating in this Website, including the Services presented, promoted, and displayed on the Website, and by clicking on “I have read and agree to the terms of use,” you hereby certify that:
  <ol type="1">
    <li> you are either a Service Professional or a prospective Service User</li>
    <li> you have the authority to enter into these Terms of Use</li>
    <li> you authorize the transfer of payment for Services requested through the use of the Website</li>
    <li> you agree to be bound by all terms and conditions of these Terms of Use and any other documents incorporated by reference herein. </li></ol>
  </p>
  <p>If you do not so agree to the foregoing, you should not click to affirm your acceptance thereof, in which case you are prohibited from accessing or using the Website. If you do not agree to any of the provisions set forth in the Terms of Use, kindly discontinue viewing or participating in this Website immediately.
  <br>YOU SPECIFICALLY AGREE THAT BY USING THE WEBSITE, YOU ARE AT LEAST 18 YEARS OF AGE AND YOU ARE COMPETENT UNDER LAW TO ENTER INTO A LEGALLY BINDING AND ENFORCEABLE CONTRACT.<br>
  All references to “you” or “your,” as applicable, mean the person that accesses, uses, and/or participates in the Website in any manner. If you use the Website or open an Account (as defined below) on behalf of a business, you represent and warrant that you have the authority to bind that business and your acceptance of the Terms of Use will be deemed an acceptance by that business and “you” and “your” herein shall refer to that business.</p>
  <h5><b>1. MODIFICATIONS TO TERMS OF USE AND/OR PRIVACY POLICY</b></h5>
  <p>Selectiall reserves the right, in its sole discretion, to change, modify, or otherwise amend the Terms of Use, and any other documents incorporated by reference herein for complying with legal and regulatory framework and for other legitimate business purposes, at any time, and Selectiall will post the amended Terms of Use at the domain of www.Selectiall.com/terms. It is your responsibility to review the Terms of Use for any changes and you are encouraged to check the Terms of Use frequently. Your use of the Website following any amendment of the Terms of Use will signify your assent to and acceptance of any revised Terms of Use. If you do not agree to abide by these or any future Terms of Use, please do not use or access the Website.</p>
  <h5><b>2. PRIVACY POLICY</b></h5>
  <p>Selectiall has established a Privacy Policy that explains to users how their information is collected and used. The Privacy Policy is referenced above and hereby incorporated into the Terms of Use set forth herein. Your use of this Website is governed by the Privacy Policy.<br><br>
  The Privacy Policy is located at: <a href="policy.php">Privacy Policy</a></p><br>

  <h4><b>B. Membership and Accessibility</b></h4><br>
  <h5><b>1. LICENSE TO ACCESS</b></h5>
  <p>Selectiall hereby grants you a non-exclusive, revocable license to use the Website as set forth in the Terms of Use; provided, however, that:
    <ol type="i">
      <li> you will not copy, distribute, or make derivative works of the Website in any medium without Selectiall’s prior written consent</li>
      <li> you will not alter or modify any part of the Website other than as may be reasonably necessary to use the Website for its intended purposes</li>
      <li> you will otherwise act in accordance with the terms and conditions of the Terms of Use and in accordance with all applicable laws.</li>
    </ol></p>
  <h5><b>2. MEMBERSHIP ELIGIBILITY CRITERIA</b></h5>
  <p>Use of the Website is available only to individuals who are at least 18 years old and can form legally binding contracts under applicable law. You represent, acknowledge and agree that you are at least 18 years of age, and that: (a) all registration information that you submit is truthful and accurate, (b) you will maintain the accuracy of such information, and (c) your use of the Website and Services offered through this Website do not violate any applicable law or regulation. Your Account (defined below) may be terminated without warning if we at our discretion, believe that you are under the age of 18 or that you are not complying with any applicable laws, rules or regulations.<br><br>
  You need not register with Selectiall to simply visit and view the Website, but to access and participate in certain features of the Website, you will need to create a password-protected account (“Account”). To create an account, you must submit your name and email address through the account registration page on the Website and create a password. You will also have the ability to provide additional optional information, which is not required to register for an account but may be helpful to Selectiall in providing you with a more customized experience when using the Website. You may also register for an Account using your existing Facebook account and log-in credentials (your “Third-Party Site Password”).<br><br>
  You are solely responsible for safeguarding your Selectiall password and, if applicable, your Third-Party Site Password (collectively, “Passwords”) at all times and shall keep your Passwords secure at all times. You shall be solely responsible for all activity that occurs on your Account and you shall notify Selectiall immediately of any breach of security or any unauthorized use of your Account. Similarly, you shall never use another’s Account without Selectiall’s permission. You agree that you will not misrepresent yourself or represent yourself as another user of the Website and/or the Services offered through the Website.<br><br>
  You hereby expressly acknowledge and agree that you yourself and not Selectiall will be liable for your losses, damages etc. (whether direct or indirect) caused by an unauthorized use of your Account. Notwithstanding the foregoing, you may be liable for the losses of Selectiall or others due to such unauthorized use.<br>
  An Account holder is sometimes referred to herein as a “Registered User.”<br><br>
  You acknowledge and agree that you shall comply with the following policies (the “Account Policies”):
    <ul>
      <li>You will not copy or distribute any part of the Website in any medium without Selectiall’s prior written authorization.</li>
      <li>You will not alter or modify any part of the Website other than as may be reasonably necessary to use the Website for its intended purpose.</li>
      <li>You will provide true, accurate, current and complete information when creating your Account and you shall maintain and update such information during the term of this Agreement so that it will remain accurate, true, current and complete.</li>
      <li>You shall not use any automated system, including but not limited to, “robots,” “spiders,” “offline readers,” “scrapers,” etc., to access the Website for any purpose without Selectiall’s prior written approval.</li>
      <li>You shall not in any manual or automated manner collect Service Professionals or Service Users information, including but not limited to, names, addresses, phone numbers, or email addresses, copying copyrighted text, or otherwise misuse or misappropriate Website information or content, including but not limited to, use on a “mirrored”, competitive, or third party site.</li>
      <li>You shall not in any way that transmits more request messages to the Selectiall servers, or any server of a Selectiall subsidiary or affiliate, in a given period of time than a human can reasonably produce in the same period by using a conventional online web browser; provided, however, that the operators of public search engines may use spiders or robots to copy materials from the site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such material. Selectiall reserves the right to revoke these exceptions either generally or in specific cases.</li>
      <li>You shall not recruit, solicit, or contact in any form Service Professionals or Service Users for employment or contracting for a business not affiliated with Selectiall without express written permission from Selectiall.</li>
      <li>You shall not take any action that
        <ol type="i">
          <li> unreasonably encumbers or, in Selectiall’s sole discretion, may unreasonably encumber the Website’s infrastructure</li>
          <li> interferes or attempts to interfere with the proper working of the Website or any third-party participation in the Website</li>
          <li> bypasses Selectiall’s measures that are used to prevent or restrict access to the Website.</li>
        </ol>
      <li>You agree not to collect or harvest any personally identifiable data, including without limitation, names or other Account information, from the Website, nor to use the communication systems provided by the Website for any commercial solicitation purposes.</li>
    </ul>
  </p>
  <h5><b>3. ADDITIONAL POLICIES</b></h5>
  <p>Your access to, use of, and participation in the Website is subject to the Terms of Use and all applicable Selectiall regulations, guidelines and additional policies that Selectiall may set forth from time to time, including without limitation, a copyright policy and any other restrictions or limitations that Selectiall publishes on the Website (the “Additional Policies”). You hereby agree to comply with the Additional Policies and your obligations thereunder at all times. You hereby acknowledge and agree that if you fail to adhere to any of the terms and conditions of this Agreement or documents referenced herein, including the Account Policies, membership eligibility criteria or Additional Policies, Selectiall, in its sole discretion, may terminate your Account at any time without prior notice to you as well as initiate appropriate legal proceedings, if necessary.</p><br>

  <h4><b>C. Member Conduct</b></h4><br>
  <h5><b>1. PROHIBITIONS ON SUBMITTED CONTENT</b></h5>
  <p>You shall not upload, post, transmit, transfer, disseminate, distribute, or facilitate distribution of any content, including text, images, video, sound, data, information, or software, to any part of the Website, including your profile (“Profile”), the posting of your Service (“Offer”), the posting of your desired Service (“Want”), or the posting of any opinions or reviews in connection with the Website, the Service, the Service Professional, or the Service User (“Feedback”) (all of the foregoing content is sometimes collectively referred to herein as “Submitted Content” and the posting of Submitted Content is sometimes referred to as a “Posting” or as “Postings”) that:
    <ul>
      <li> misrepresents the source of anything you post, including impersonation of another individual or entity or any false or inaccurate biographical information for any Service Professionals; provides or create links to external sites that violate the Terms of Use; is intended to harm or exploit any individual under the age of 18 (“Minor”) in any way; is designed to solicit, or collect personally identifiable information of any Minor, including, but not limited to, name, email address, home address, phone number, or the name of his or her school</li>
      <li> invades anyone’s privacy by attempting to harvest, collect, store, or publish private or personally identifiable information, such as names, email addresses, phone numbers, passwords, account information, credit card numbers, home addresses, or other contact information without their knowledge and willing consent;
      <li> contains falsehoods or misrepresentations that could damage Selectiall or any third party</li>
      <li>  is pornographic, harassing, hateful, illegal, obscene, defamatory, libelous, slanderous, threatening, discriminatory, racially, culturally or ethnically offensive; incites, advocates, or expresses pornography, obscenity, vulgarity, profanity, hatred, bigotry, racism, or gratuitous violence; encourages conduct that would be considered a criminal offense, give rise to civil liability or violate any law; promotes racism, hatred or physical harm of any kind against any group or individual; contains nudity, violence or inappropriate subject matter; or is otherwise inappropriate</li>
      <li> is copyrighted, protected by trade secret or otherwise subject to third-party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from the rightful owner to post the material and to grant Selectiall all of the license rights granted herein;
      contains or promotes an illegal or unauthorized copy of another person’s copyrighted work, such as pirated computer programs or links to them, information to circumvent manufacture installed copy-protection devices, pirated music or links to pirated music files, or lyrics, guitar tabs or sheet music, works of art, teaching tools, or any other item the copy, display, use, performance, or distribution of which infringes on another’s copyright, intellectual property right, or any other proprietary right</li>
      <li> is intended to threaten, stalk, defame, defraud, degrade, victimize, or intimidate an individual or group of individuals for any reason on the basis of age, gender, disability, ethnicity, sexual orientation, race, or religion; or to incite or encourage anyone else to do so</li>
      <li> intends to harm or disrupt another user’s computer or would allow others to illegally access software or bypass security on websites or servers, including but not limited, to spamming; impersonates, uses the identity of, or attempts to impersonate a Selectiall employee, agent, manager, host, another user, or any other person though any means</li>
      <li> advertises or solicits a business not related to or appropriate for the Website (as determined by Selectiall in its sole discretion)</li>
      <li> contains or could be considered “junk mail”, “spam”, “chain letters”, “pyramid schemes”, “affiliate marketing”, or unsolicited commercial advertisement</li>
      <li> contains advertising for ponzi schemes, discount cards, credit counseling, online surveys or online contests</li>
      <li> distributes or contains viruses or any other technologies that may harm Selectiall, or the interests or property of Selectiall users</li>
      <li> contains links to commercial services or websites, except as allowed pursuant to the Terms of Use;is non-local or irrelevant content</li>
      <li> contains identical content to other open Postings you have already posted; or uses any form of automated device or computer program that enables the submission of Postings without the express written consent of Selectiall</li>
    </ul></p>
    <h5><b>2. PROHIBITIONS ON SENDING MESSAGES</b></h5>
    <p>You will not send messages to other users containing:
      <ul>
        <li>offers to make national or international money transfers for amounts exceeding the asking price of a service, with intent to request a refund of any portion of the payment</li>
       <li>unsolicited advertising or marketing of a service not offered on the Website or an external website</li>
     </ul></p>
    <h5><b>3. NO DISCRIMINATION</b></h5>
    <p>Discriminatory Postings. Indian laws prohibit any preference, limitation or discrimination based on race, color, religion, sex, national origin, age, handicap or other protected class. Selectiall will not knowingly accept any Posting which is in violation of the law. Selectiall has the right, in its sole discretion and without prior notice to you; to immediately remove any posting that discriminates or is any way in violation of any law.</p>
    <h5><b>4. PROHIBITIONS WITH RESPECT TO SERVICES</b></h5>
    <p>While using the Website, you shall not:
      <ul>
        <li> post content or items in any inappropriate category or areas on the Website</li>
        <li> violate any laws, third-party rights, Account Policies, or any provision of the Terms of Use, such as the prohibitions described above</li>
        <li> fail to deliver payment for Services purchased by you, unless the Service Professional has materially changed the description of the Service description after you negotiate an agreement for such Service, a clear typographical error is made, or you cannot authenticate the Service Professional’s identity</li>
        <li> fail to perform Services purchased from you, unless the Service User fails to materially meet the terms of the mutually agreed upon agreement for the Services, refuses to pay, a clear typographical error is made, or you cannot authenticate the Service User’s identity; manipulate the price of any Service or interfere with other users’ Postings</li>
        <li> circumvent or manipulate our fee structure, the billing process, or fees owed to Selectiall; post false, inaccurate, misleading, defamatory, or libelous content (including personal information about any Website user)</li>
        <li> take any action that may undermine the Feedback or ratings systems (such as displaying, importing or exporting Feedback information off of the Website or using it for purposes unrelated to the Website)</li>
      </ul></p>
    <h5><b>5. FEEDBACK</b></h5>
    <p>As a participant in the Website, you agree to use careful, prudent, and good judgment when leaving Feedback for another user. The following actions constitute inappropriate uses of Feedback:
      <ol type="a">
        <li> threatening to leave negative or impartial Feedback for another user unless that user provides services not included in the original Posting or not agreed to as part of the Service to be provided</li>
        <li> leaving Feedback in order to make the Service Professional or Service User appear better than he or she actually is or was</li>
        <li> including conditions in an Offer or Want that restrict a Service Professional or a Service User from leaving Feedback.</li>
      </ol></p>
    <p>
      <ol type="1">
        <li>Sanctions for Inappropriate Use of Feedback. If you violate any of the above-referenced rules in connection with leaving Feedback, Selectiall, in its sole discretion, may take any of the following actions:
          <ol type="i">
            <li> cancel your Feedback or any of your Postings</li>
            <li> limit your Account privileges</li>
            <li> suspend your Account and/or decrease your status earned via the Feedback page.</li>
          </ol></li>
        <li>Reporting Inappropriate Use of Feedback. You may contact Selectiall regarding any inappropriate use of Feedback via-email at support@Selectiall.com.</li>
        <li>Resolving Disputes in Connection with Feedback. In the event of any dispute between users of the Website concerning Feedback, Selectiall shall be the final arbiter of such dispute. Further, IN THE EVENT OF ANY DISPUTE BETWEEN USERS OF THE WEBSITE CONCERNING FEEDBACK, SELECTIALL HAS THE RIGHT, IN ITS SOLE AND ABSOLUTE DISCRETION, TO REMOVE SUCH FEEDBACK OR TAKE ANY ACTION IT DEEMS REASONABLE WITHOUT INCURRING ANY LIABILITY THEREFROM.</li>
      </ol></p>
    <p>The foregoing lists of prohibitions provide examples and are not complete or exclusive. Selectiall reserves the right to:
      <ol type="a">
        <li> terminate your access to your Account, your ability to post to this Website (or the Services)</li>
        <li> refuse, delete or remove, move or edit the content, in whole or in part, of any Postings; with or without cause and with or without notice, for any reason or no reason, or for any action that Selectiall determines is inappropriate or disruptive to this Website or to any other user of this Website and/or Services.</li>
      </ol></p>
    <p>Selectiall reserves the right to restrict the number of e-mails or other messages that you are allowed to send to other users to a number that Selectiall deems appropriate in Selectiall’s sole discretion. Selectiall may report to law enforcement authorities any actions that may be illegal, and any reports it receives of such conduct. When legally required or at Selectiall’s discretion, Selectiall will cooperate with law enforcement agencies in any investigation of alleged illegal activity on this Website or on the Internet. Selectiall does not and cannot review every Posting posted to the Website. These prohibitions do not require Selectiall to monitor, police or remove any Postings or other information submitted by you or any other user.</p><br>

    <h4><b>D. Member Conduct</b></h4><br>
    <h5><b>1. PROFILES AND OFFERS MUST NOT BE FRAUDULENT</b></h5>
    <p>Subject to any exceptions set forth in these Terms of Use or Additional Policies, if any, Service Professionals shall not:
      <ol type="a">
        <li> list services or offers relating to any Service in a category that is inappropriate to the Service they are offering</li>
        <li> misrepresent the location at which they will provide a Service</li>
        <li> include brand names or other inappropriate keywords in their Profile, Offer, Want, Feedback, or any other title or description relating to a Service</li>
        <li> use misleading titles that do not accurately describe the Service</li>
        <li> include any information in their Profile that is fraudulent.</li></ol></p>
    <h5><b>2. PROFILES AND OFFERS CANNOT USE TECHNIQUES TO AVOID OR CIRCUMVENT SELECTIALL FEES</b></h5>
    <p>Subject to any exceptions set forth in these Terms of Use or Additional Policies, if any, Service Professionals shall not:
      <ol type="a">
        <li> offer a catalog or a link to a third-party website from which Service Users or any Registered User or user of the Website may obtain the Service directly</li>
        <li> exceed multiple Posting limits</li>
        <li> post a single Service but offer additional identical services in the Service description</li>
        <li> charge fees for traveling further than desired to provide the Service</li>
        <li> offer the opportunity through Selectiall to purchase the Service or any other service outside of Selectiall</li>
        <li> use their Profile page or user name to promote services not offered on or through the Website and/or prohibited services.</li>
      </ol>
      In case we realize that any professional is involved in any of the above activities, Selectiall holds the sole discretion to blacklist the professional and withhold any outstanding credits or payments to the professional.</p>
      <h5><b>3. PROFILES AND OFFERS MUST PROMOTE A FAIR PLAYING FIELD AND PROVIDE A SAFE, SIMPLE, AND POSITIVE EXPERIENCE FOR ALL WEBSITE USERS</b></h5>
      <p>Subject to any exceptions set forth in these Terms of Use or Additional Policies, if any, Service Professionals shall not:
        <ol type="a">
          <li> solicit Service Users to mail cash or use other payment methods not specifically permitted by Selectiall as approved payment methods</li>
          <li> include links that do not conform to Selectiall’s policies with respect to third-party links</li>
          <li> use certain types of HTML and JavaScript in Postings, your Profile page, your Offer page, or your Wants page</li>
          <li> promote raffles, prizes, bonuses, games of chance, giveaways, or random drawings</li>
          <li> use profanity in any Posting</li>
          <li> acknowledge or credit a third-party service professional for services or products directly connected with your particular Posting:
            <ol type="1">
              <li> with more than 10 words of text at HTML font size greater than 3 and/or a logo of 88X33 pixels (provided that you represent and warrant that you have the necessary rights, licenses, permissions and/or authorizations from the applicable third party to use that third party’s name and/or logo)</li>
              <li> with any promotional material in connection with that third-party company</li>
              <li> with a link to the third-party’s website with any information in addition to the Service provided via Selectiall</li>
            </ol>
          </li>
          <li> include third-party endorsements in a Posting; or (h) create a Posting that does not offer a Service.</li></ol></p>
      <h5><b>4. CONSENT FOR REACHING OUT VIA PHONE CALL, SMS, EMAIL OR ANY OTHER FORM OF ELECTRONIC COMMUNICATION</b></h5>
      <p>It is further clarified that your registration on the Website shall be deemed to be your consent to be contacted for the purposes mentioned above:
        <ol type="i">
          <li> on the mobile number shared by you even if you are registered with the National Customer Preference Register (NCPR) and have opted out of receiving promotional calls and messages</li>
          <li> by way of SMS or email notifications or messages in any other electronic form</li></ol></p>
      <h5><b>5. SANCTIONS FOR VIOLATING ANY OF THE RULES FOR SERVICE PROFESSIONALS</b></h5>
      <p>If a Service Professional violates any of the above-referenced rules in connection with his or her Posting, Selectiall, in its sole discretion, may take any of the following actions:
        <ol type="a">
          <li> cancel the Posting</li>
          <li> limit the Service Professional’s Account privileges</li>
          <li> suspend the Service Professional’s Account</li>
          <li> cause the Service Professional to forfeit any fees earned on a cancelled Posting</li>
          <li> decrease the Service Professional’s status earned via the Feedback page</li></ol></p><br>

      <h4><b>E. Rules for Service Users</b></h4><br>
      <h5><b>1. SERVICE USERS SHALL NOT TAKE ANY OF THE FOLLOWING ACTIONS:</b></h5>
      <p><ol type="a">
        <li> commit to purchasing or using a Service without paying</li>
        <li> sign up for, negotiate a price for, use, or otherwise solicit a Service with no intention of following through with your use of or payment for the Service</li>
        <li> agree to purchase a Service when you do not meet the Service Professional’s terms as outlined in the Posting, or agree to purchase a Service with the intention of disrupting a Posting</li>
        <li> misuse any options made available now or in the future by Selectiall in connection with the use or purchase of any Service</li></ol></p>
      <h5><b>2. SANCTIONS FOR VIOLATING ANY OF THE RULES FOR SERVICE USERS</b></h5>
      <p>If a Service User violates any of the above-referenced rules in connection with his or her Posting, Selectiall, in its sole discretion, may take any of the following actions:
        <ol type="a">
          <li> cancel the Posting</li>
          <li> limit the Service User’s Account privileges</li>
          <li> suspend the Service User’s Account</li>
          <li> decrease the Service User’s status earned via the Feedback page.</li></ol></p><br>

      <h4><b>F. Use of Submitted Content</b></h4><br>
      <h5><b>1. NO CONFIDENTIALITY</b></h5>
      <p>The Website may now or in the future permit the submission of videos or other communications submitted by you and other users, including without limitation, your Profile, your Offer, your Wants, any Feedback, and all Submitted Content, and the hosting, sharing, and/or publishing of such Submitted Content. You understand that whether or not such Submitted Content is published, Selectiall does not guarantee any confidentiality with respect to any Submitted Content.
      You agree that any Submitted Content provided by you for which you authorize to be searchable by Registered Users who have access to the Website is provided on a non-proprietary and non confidential basis. You agree that Selectiall shall be free to use or disseminate such freely searchable Submitted Content on an unrestricted basis for the purpose of providing the Services.
      You are aware that any information provided by you in the Submitted Content towards locating a professional who ordinarily is bound to maintain confidentiality under law with his/her client (i.e. a doctor or a lawyer) is not extended to Selectiall.
      Selectiall may also disclose user information including personal information if Selectiall reasonably believes that disclosure:
      <ol type="i">
        <li> is necessary in order to comply with a legal process (such as a court order, search warrant, etc.) or other legal requirement of any governmental authority</li>
        <li> would potentially mitigate Selectiall’s liability in an actual or potential lawsuit</li>
        <li> is otherwise necessary or appropriate to protect our rights or property, or the rights or property of any person or entity</li>
        <li> to enforce this Agreement (including, but not limited to ensuring payment of fees by users)</li>
        <li> as may be required or necessary to deter illegal behavior (including, but not limited to, fraud).</li></ol></p>
      <h5><b>2. YOUR REPRESENTATIONS AND WARRANTIES</b></h5>
      <p>You shall be solely responsible for your own Submitted Content and the consequences of posting or publishing it. In connection with Submitted Content, you affirm, represent, and/or warrant that:
      <ol type="a">
        <li> you own or have the necessary licenses, rights, consents, and permissions to use and authorize Selectiall to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all Submitted Content to enable inclusion and use of the Submitted Content in the manner contemplated by the Website and these Terms of Use</li>
        <li> you have the written consent, release, and/or permission of each and every identifiable individual person in the Submitted Content to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the Submitted Content in the manner contemplated by the Website and these Terms of Use</li>
        <li> you agree to pay for all royalties, fees, and any other monies owing any person by reason of any Submitted Content posted by you to or through the Website</li></ol></p>
      <h5><b>3. YOUR OWNERSHIP RIGHTS AND LICENSE TO SELECTIALL</b></h5>
      <p>You retain all of your ownership rights in your Submitted Content. However, by submitting the Submitted Content to Selectiall for posting on the Website, you hereby grant, and you represent and warrant that you have the right to grant, to Selectiall a perpetual, worldwide, non-exclusive, royalty-free, sublicense able and transferable license to link to, use, reproduce, distribute, reformat, translate, prepare derivative works of, display, and perform the Submitted Content in connection with the Website and Selectiall’s (and its successor’s) business operations, including without limitation, for the promotion and redistribution of any part or all of the Website, and any derivative works thereof, in any media formats and through any media channels. You also hereby grant each user of the Website a non-exclusive license to access your Submitted Content through the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such Submitted Content as permitted through the functionality of the Website and under these Terms of Use. The foregoing license granted by you terminates once you remove or delete the Submitted Content from the Website. You acknowledge and understand that the technical processing and transmission of the Website, including your Submitted Content, may involve:
      <ol type="a">
        <li> transmissions over various networks</li>
        <li> changes to conform and adapt to technical requirements of connecting networks or devices</li></ol>
      You may remove your Submitted Content from the Website at any time. If you choose to remove your Submitted Content, the license granted above will automatically expire.</p>
      <h5><b>4. SELECTIALL’S DISCLAIMERS AND RIGHT TO REMOVE</b></h5>
      <p>Selectiall does not endorse any Submitted Content or any opinion, recommendation, or advice expressed therein, and Selectiall expressly disclaims any and all liability in connection with all Submitted Content. Selectiall does not permit copyright infringing activities and infringement of intellectual property rights on the Website, and Selectiall will remove any Data (as defined below) or Submitted Content if properly notified, pursuant to the “take down” notification procedure described in Section J below, that such Posting or Submitted Content infringes on another’s intellectual property rights. Selectiall reserves the right to remove any Data or Submitted Content without prior notice. Selectiall will also terminate a user’s access to the Website, if he or she is determined to be a repeat infringer. A repeat infringer is a Website user who has been notified of infringing activity more than twice and/ or has had Submitted Content removed from the Website more than twice. Selectiall also reserves the right, in its sole and absolute discretion, to decide whether any Data or Submitted Content is appropriate and complies with these Terms of Use for all violations, in addition to copyright infringement and violations of intellectual property law, including, but not limited to, pornography, obscene or defamatory material, or excessive length. Selectiall may remove such Submitted Content and/or terminate a user’s access for uploading such material in violation of these Terms of Use at any time, without prior notice and in its sole discretion.<br><br>You acknowledge and understand that when using the Website, you will be exposed to Submitted Content from a variety of sources, and that Selectiall is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Submitted Content. You further acknowledge and understand that you may be exposed to Submitted Content that is inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Selectiall with respect thereto, and agree to indemnify and hold Selectiall, its owners, members, managers, operators, directors, officers, agents, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the Website.<br><br>You are solely responsible for the photos, profiles and other content, including, without limitation, Submitted Content that you publish or display on or through the Website, or transmit to other Website users. You understand and agree that Selectiall may, in its sole discretion and without incurring any liability, review and delete or remove any Submitted Content that violates this Agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of Website users or others.</p>
      <h5><b>5. Suggestions</b></h5>
      <p>If you send or transmit any communications, comments, questions, suggestions, or related materials to Selectiall, whether by letter, email, telephone, or otherwise (collectively, “Suggestions”), suggesting or recommending changes to the Website, including, without limitation, new features or functionality relating thereto, all such Suggestions are, and will be treated as, non-confidential and non-proprietary. You hereby assign all right, title, and interest in, and Selectiall is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Suggestions, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Suggestions. You understand and agree that Selectiall is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Suggestions, and you have no right to compel such use, display, reproduction, or distribution or seek recognition if the Suggestions are in fact implemented.</p><br>

      <h4><b>G. Copyright Infringement Take Down Procedure</b></h4><br>
      <p>Selectiall has high regard for intellectual property and expects the same level of standard to be employed by its users. Selectiall may, in appropriate circumstances and at its discretion, terminate the Account or prohibit access to the Website of users who infringe upon the intellectual property rights of others.
      If you believe that your work has been copied and posted on the Website in a way that constitutes copyright infringement and/or trademark infringement, please send the following information to us at <a href="mailto: help@selectiall.com">help@Selectiall.com</a>
      <ol type="i">
        <li> identification of the copyrighted and/or trademarked work claimed to have been infringed, or, if multiple works at a single online site are covered by a single notification, a representative list of such works at that site</li>
        <li> identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled at the Website, and information reasonably sufficient to permit Selectiall to locate the material</li>
        <li> a written statement that you have a good faith belief that the disputed use is not authorized by the copyright and/or trademark owner, its agent, or the law</li>
        <li> information reasonably sufficient to permit Selectiall to contact you as the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted</li>
        <li> an electronic or physical signature of the person authorized to act on behalf of the owner of an exclusive interest that is allegedly infringed</li>
        <li> a statement by you, made under penalty of perjury, that the information in your report is accurate and that you are the owner of the exclusive right or authorized to act on the behalf of the owner of the exclusive right. A statement by you comprised of the foregoing points is referred to herein as the “Notice.”</li></ol>
      <i>Only the intellectual property rights owner is permitted to report potentially infringing items through Selectiall’s reporting system set forth above. If you are not the intellectual property rights owner, you should contact the intellectual property rights owner and they can choose whether to use the procedures set forth in these Terms of Use.</i></p><br>

      <h4><b>H. Modifications to or Termination of Website</b></h4><br>
      <h5><b>1. MODIFICATION OR CESSATION OF WEBSITE</b></h5>
      <p>Selectiall reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Website (or any part thereof) with or without notice and in its sole discretion. You agree that Selectiall shall not be liable to you or to any third party for any modification, suspension or discontinuance of Selectiall services.</p>
      <h5><b>2. TERMINATION BY SELECTIALL</b></h5>
      <p>You hereby acknowledge and agree that Selectiall, in its sole and absolute discretion, has the right (but not the obligation) to delete, terminate, or deactivate your Account, block your email or IP address, cancel the Website or otherwise terminate your access to or participation in the use of the Website (or any part thereof), or remove and discard any Submitted Content on the Website (“Termination of Service”), immediately and without notice, for any reason, including without limitation, Account inactivity or if Selectiall believes or has reason to believe that you have violated any provision of the Terms of Use.</p>
      <h5><b>3. TERMINATION BY YOU</b></h5>
      <p>You may cancel your use of the Website and/or terminate the Terms of Use with or without cause at any time by following the link in your Account under “Account Preferences” to “Deactivate Account.”</p>
      <h5><b>4. EFFECT OF TERMINATION</b></h5>
      <p>Upon termination of your Account, your right to participate in the Website, including, but not limited to, your right to offer or purchase Services and your right to receive any fees or compensation, including, without limitation, referral discounts, incentive bonuses, or other special offer rewards, shall automatically terminate. You acknowledge and agree that your right to receive any fees or compensation hereunder is conditional upon your proper use of the Website, your adherence to the Terms of Use, the continuous activation of your Account, and your permitted participation in the Website. In the event of Termination of Service, your Account will be disabled and you may not be granted access to your Account or any files or other data contained in your Account. Notwithstanding the foregoing, residual data may remain in the Selectiall system.<br><br>Unless Selectiall has previously cancelled or terminated your use of the Website (in which case subsequent notice by Selectiall shall not be required), if you provided a valid email address during registration, Selectiall will notify you via email of any such termination or cancellation, which shall be effective immediately upon Selectiall’s delivery of such notice.<br><br>Upon Termination of Service, the following shall occur: all licenses granted to you hereunder will immediately terminate; and you shall promptly destroy all copies of Selectiall Data (as defined below), Marks (as defined below) and other content in your possession or control. You further acknowledge and agree that Selectiall shall not be liable to you or any third party for any termination of your access to the Website. Upon Termination of Service, Selectiall retains the right to use any data collected from your use of the Website for internal analysis and archival purposes, and all related licenses you have granted Selectiall hereunder shall remain in effect for the foregoing purpose. In no event is Selectiall obligated to return any Submitted Content to you. Sections K, L, M, N, O, Q, R, S, T, U, V, W, and X, shall survive expiration or termination of the Website or your Account.<br><br>You agree to indemnify and hold Selectiall, and its officers, managers, members, affiliates, successor, assigns, directors, agents, service professionals, suppliers, and employees harmless from any claim or demand, including reasonable attorneys’ fees and court costs, made by any third party due to or arising out of the Termination of Service.</p><br>

      <h4><b>I. Intellectual Property Rights</b></h4><br>
      <h5><b>1. SELECTIALL OWNS OR HOLDS THE LICENSES TO ALL DATA AND MARKS ON THE WEBSITE</b></h5>
      <p>The content on the Website (exclusive of all Submitted Content), including without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like (“Data”) and the trademarks, service marks and logos contained therein (“Marks”), are owned by Selectiall. Other trademarks, names and logos on this Website are the property of their respective owners.<br><br>Data on the Website is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. Selectiall reserves all rights not expressly granted in and to the Website and the Data. You agree not to use, copy, or distribute, any of the Data other than as expressly permitted herein, including any use, copying, or distribution of Submitted Content obtained through the Website for any commercial purposes. If you download or print a copy of the Data for personal use, you must retain all copyright and other proprietary notices contained thereon. You agree not to circumvent, disable or otherwise interfere with security features of the Website or features that prevent or restrict use or copying of any Data or enforce limitations on use of the Website or the Data therein.</p>
      <h5><b>2. SELECTIALL’S LICENSE TO YOU FOR THE USE OF DATA AND MARKS</b></h5>
      <p>The Website contains Selectiall’s Data and Marks, which are, or may become, protected by copyright, trademark, patent, trade secret and other laws, and Selectiall owns and retains all rights in the Selectiall Data and Marks. Subject to these Terms of Use, Selectiall hereby grants you a limited, revocable, nontransferable, nonsublicensable license to reproduce and display the Selectiall Data (excluding any software source code) solely for your personal use in connection with accessing and participating in the Website.<br><br>The Website may also contain Data of other users or licensors, which you shall not copy, modify, translate, publish, broadcast, transmit, distribute, perform, display, or sell.</p><br>

      <h4><b>J. Selectiall Fees</b></h4><br>
      <h5><b>1. FEES INCURRED BY SERVICE PROFESSIONALS</b></h5>
      <p>Joining Selectiall, opening an Account, posting Services and viewing posted Services is free. Selectiall reserves the right at its sole discretion to charge fees to Service Professionals for other services that Selectiall may provide in the future.<br><br>Selectiall may also in certain categories require Service Professionals to make payments for following up on job leads i.e. requests posted by Service Users, and permitting the Service Professional to contact the Service User (“Lead Fee”) irrespective of whether the job leads eventually result in a transaction or exchange of consideration for the service requested. In order to be eligible to make such Lead Fee payment, Service Professionals shall be required to make advance payments (“Credits”) from which the Lead Fee may be deducted as and when necessary. Whenever the Credits fall below the prescribed threshold, the Service Professional shall be prompted to refill the Credits in order to continue enjoying the ability to follow up on leads and contacting Service Users.<br><br>The service professional is entitled to refund of credits that is credited back in their wallet in the following conditions:
        <ol type="1">
          <li> Refunds are processed when customer cancels request</li>
          <li> Refunds are processed if the customer has not viewed quote and not cancelled request 4 days after your response</li></ol>
        In the event:<ol type="i">
        <li> the job lead is identified to be non-genuine</li>
        <li> the Service User within 48 hours of posting a request on the Website withdraws the same by way of the Website or the mobile application only</li>
        <li> the Service Professional pays the Lead Fee to respond to the Service User’s request for service but the Service User does not open or access the Service Professional’s response</li></ol>
        &nbsp;&nbsp;&nbsp;the Lead Fee shall be reimbursed to the Service Professional. The decision of Selectiall pertaining to the above shall be final and binding.<br><br>
        Selectiall offers premium services to Service Professionals for a fee and may in the future offer additional services, like tax preparation and bookkeeping that Service Professionals can also choose to purchase. Selectiall reserves the right to charge fees for these services at its sole discretion.</p>
      <h5><b>2. FEES INCURRED BY SERVICE USERS</b></h5>
      <p>Joining Selectiall, opening an Account, viewing posted Services, and bidding on posted Services is free. Selectiall currently does not charge Service Users for transactions completed on the Website between Service Users and Services Professionals. However, Selectiall reserves the right to charge a fee to Service Users in the future on a per-transaction basis or in any other manner, and reserves the right to do so in its sole discretion. Changes to this Fee Policy are effective after Selectiall has provided you with thirty (30) days’ notice by posting the changes on the Website.<br><br>If applicable, you agree to pay all fees or charges to your Account based on Selectiall’s fees, charges, and billing terms then in effect. If you do not pay on time or if Selectiall cannot charge your credit card, any payment gateway or other payment method for any reason, Selectiall reserves the right to either suspend or terminate your access to the Website and Account and terminate these Terms of Use. You are expressly agreeing that Selectiall is permitted to bill you for the applicable fees, any applicable tax and any other charges you may incur in connection with your use of this Website and the fees will be billed to your credit card, a payment gateway or other payment method designated at the time you make a purchase or register for a fee-based service. If you cancel your Account at any time, you will not receive any refund. If you have a balance due on any account, you agree that Selectiall may charge such unpaid fees to your credit card or otherwise bill you for such unpaid fees. Selectiall reserves its right to initiate appropriate legal proceedings, if necessary, in its sole discretion, to recover such outstanding amounts.</p>
      <h5><b>3. TAXES</b></h5>
      <p>You understand that we are acting solely as an intermediary for the collection of rents and fees between a Service User and a Service Professional who choose to enter into an Agreement for Service. Because state and local tax laws vary significantly by locality, you understand and agree that you are solely responsible for determining your own tax reporting requirements in consultation with tax advisors, and that we cannot and do not offer tax advice to either hosts or guests. Further, you understand that Selectiall shall not be responsible or liable in any manner in relation to tax liability of a Service User or a Service Professional.</p>
      <h5><b>4. REFUND POLICY</b></h5>
      <p>All commissions payable to Selectiall by Service Professionals on consummated transactions, i.e. exchange of services for consideration, are final and non-refundable. All monies paid by Service Professionals in form of “Credits” are non-interest bearing and shall be refunded to the Service Professionals if they remain un-utilised for a period greater than 364 days only. Such amounts shall not be refunded prior to that.</p><br>

      <h4><b>K. Negotiation of Terms of Service; Disputes Between Registered Users</b></h4><br>
      <h5><b>1. NEGOTIATION WORKSHEET AND CONTRACT TEMPLATE</b></h5>
      <p>As a courtesy to Registered Users, to facilitate the negotiation and confirmation of the Agreement for Service, Selectiall provides a general framework for negotiating the terms of Service (e.g., rate) (“Negotiation Worksheet”). Registered Users acknowledge and agree that (i) they are solely responsible for addressing all issues that exist now or may arise in the future in connection with the applicable Service; and (ii) it is solely up to such Registered Users, if they so desire, to enter into a signed, written contract, that addresses all of the relevant issues and memorializes the agreed upon Negotiation Worksheet.<br><br>You should not rely on the any information or resources contained on the Website, including, without limitation, the Negotiation Worksheet, as a replacement or substitute for any professional, financial, legal or other advice or counsel. Selectiall makes no representations and warranties, and expressly disclaims any and all liability, concerning actions taken by a user following the information or using the resources offered or provided on or through the Websites, including, without limitation, the Negotiation Worksheet. In no way will Selectiall be responsible for any actions taken or not taken based on the information or resources provided on this Website. If you have a situation that requires professional advice, you should consult a qualified specialist. Do not disregard, avoid or delay obtaining professional advice from a qualified specialist because of information or resources that are provided on this Website, however provided.</p>
      <h5><b>2. SELECTIALL IS NOT A PARTY TO ANY SERVICE CONTRACT</b></h5>
      <p>Each Registered User hereby acknowledges and agrees that Selectiall is NOT a party to any oral or written Agreement for Service, Negotiation Worksheet, or any contract entered into between Registered Users in connection with any Service offered, directly or indirectly, through the Website. Each Registered User acknowledges, agrees and understands that Selectiall only seeks to provide a platform wherein the Service User and Service Professional can be brought together and Selectiall itself has not role in the execution or provision of Services.</p>
      <h5><b>3. NO AGENCY OR PARTNERSHIP</b></h5>
      <p>No agency, partnership, joint venture, or employment is created as a result of the Terms of Use or your use of any part of the Website, including without limitation, the Negotiation Worksheet or Agreement for Service. You do not have any authority whatsoever to bind Selectiall in any respect. All Service Professionals are independent contractors. Neither Selectiall nor any users of the Website may direct or control the day-to-day activities of the other, or create or assume any obligation on behalf of the other.</p>
      <h5><b>4. DISPUTES BETWEEN REGISTERED USERS</b></h5>
      <p>Subject to the provisions regarding disputes between Website participants in connection with Feedback, your interactions with individuals and/or organizations found on or through the Website, including payment of and performance of any Service, and any other terms, conditions, warranties or representations associated with such transactions or dealings, are solely between you and such individual or organization. You should take reasonable precautions and make whatever investigation or inquiries you deem necessary or appropriate before proceeding with any online or offline transaction with any third party, including without limitation, service professionals and Service Users.<br><br>You understand that deciding whether to use the Services of a Service Professional or provide Services to a Service User or use information contained in any Submitted Content, including, without limitation, Postings, Offers, Wants and/or Feedback, is your personal decision for which alone are responsible. You understand that Selectiall does not warrant and cannot make representations as to the suitability of any individual you may decide to interact with on or through the Website and/or the accuracy or suitability of any advice, information, or recommendations made by any individual. While Selectiall may attempt to seek information about the background of a Service Professional, either via a telephonic or in-person interview, review of past work/customer feedback and/or check presence online (if available) on Facebook, personalised website, LinkedIn, Twitter etc., you understand that Service Professionals may register themselves suo moto. You also understand that any so called background check undertaken by Selectiall is not exhaustive to the extent to determine previous criminal antecedents and hence, at the end of the day, the Service User should take an informed decision on his/her own accord and keep in mind the fact that Selectiall only seeks to provide a platform wherein Service Users and Service Professionals have an opportunity to meet each other.<br><br>
      NOTWITHSTANDING THE FOREGOING, YOU AGREE THAT SINCE SELECTIALL only seeks to provide a platform wherein the Service User and Service Professional can be brought together and Selectiall itself has not role in the execution or provision of Services ITSELF, URBAN CLAP SHALL NOT BE RESPONSIBLE OR LIABLE FOR ANY LOSS OR DAMAGE OF ANY SORT WHATSOEVER INCURRED AS THE RESULT OF ANY SUCH TRANSACTION OR DEALINGS. IF THERE IS A DISPUTE BETWEEN PARTICIPANTS ON THE WEBSITE, OR BETWEEN REGISTERED USERS OR ANY WEBSITE USER AND ANY THIRD PARTY, YOU ACKNOWLEDGE AND AGREE THAT SELECTIALL IS UNDER NO OBLIGATION TO BECOME INVOLVED. IN THE EVENT THAT A DISPUTE ARISES BETWEEN YOU AND ONE OR MORE WEBSITE USERS, REGISTERED USERS OR ANY THIRD PARTY, YOU HEREBY RELEASE SELECTIALL, ITS OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, ATTORNEYS, AGENTS, AND SUCCESSORS IN RIGHTS FROM ANY CLAIMS, DEMANDS, AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND OR NATURE, KNOWN OR UNKNOWN, SUSPECTED OR UNSUSPECTED, FORESEEABLE OR UNFORESEEABLE, DISCLOSED OR UNDISCLOSED, ARISING OUT OF OR IN ANY WAY RELATED TO SUCH DISPUTES AND/OR THE WEBSITE OR ANY SERVICE PROVIDED THEREUNDER.
    </p><br>

      <h4><b>L. Dispute Resolution</b></h4><br>
      <p>If a dispute arises between you and Selectiall, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, you and Selectiall hereby agree that we will resolve any claim or controversy at law and equity that arises out of the Terms of Use or the Website in accordance with this Section O or as we and you otherwise agree in writing. Before resorting to the filing of a formal lawsuit, we strongly encourage you to first contact us directly to seek a resolution via e-mail at <a href="mailto: support@selectiall.com">support@Selectiall.com</a>. The dispute shall be resolved through alternative dispute resolution procedures, such as mediation or arbitration, as alternatives to litigation.</p>
      <h5><b>1. GOVERNING LAW</b></h5>
      <p>The Terms of Use shall be governed in all respects by the laws of India and any legal proceeding arising out of this Agreement will occur exclusively in the courts located in New Delhi, India.</p>
      <h5><b>2. ADVERTISEMENTS</b></h5>
      <p>Aspects of the Website and other Selectiall services may be supported by advertising revenue. As such, Selectiall may display advertisements and promotions on the service. The manner, mode and extent of advertising by Selectiall on the Website are subject to change and the appearance of advertisements on the Website does not necessarily imply endorsement by Selectiall of any advertised products or services. You agree that Selectiall shall not be responsible or liable for any loss or damage of any sort incurred by you as a result of any such dealings or as the result of the presence of such advertisers on the Website.</p><br>

      <h4><b>M. Third-party Links, Contact Forms and Phone Numbers</b></h4><br>
      <p>The Website may provide, or third parties may provide, links, contact forms and/or phone numbers to other websites or resources, including, without limitation, social networking, blogging and similar websites through which you are able to log into the Website using your existing account and log-in credentials for such third-party websites. Certain areas of the Website may allow you to interact and/or conduct transactions with such third-party sites, and, if applicable, allow you to configure your privacy settings in your third-party site account to permit your activities on the Website to be shared with your contacts in your third-party site account. Because Selectiall has no control over such sites and resources, you acknowledge and agree that Selectiall is not responsible for the availability of such external sites or resources, and is not responsible or liable for any content, advertising, products, goods or services on or available from such websites or resources. Unless expressly stated on the Website, links to third-party sites should in no way be considered as or interpreted to be Selectiall’s endorsement of such third-party sites or any product or service offered through them. You further acknowledge and agree that Selectiall shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, advertising, product, goods or services available on or through any such website or resource. The Third-party website may have different privacy policies and terms and conditions and business practices than Selectiall. In certain situations, you may be transferred to a Third-party website through a link or connected to a Third-party resource by a contact form or phone but it may appear that you are still on this Website or transacting with Selectiall. In these situations, you acknowledge and agree that the Third-party website terms and conditions and privacy policy apply in this situation. Your dealings and communications through the Website with any party other than Selectiall are solely between you and such third party. Any complaints, concerns or questions you have relating to materials provided by third parties should be forwarded directly to the applicable third party.</p><br>

      <h4><b>N. Disclaimer of Warranties</b></h4><br>
      <p>YOU AGREE THAT YOUR USE OF THE WEBSITE SHALL BE AT YOUR OWN RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, AND SELECTIALL AND ITS OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, SUCCESSORS, ASSIGNS, SUBSIDIARIES, AFFILIATES, SERVICE PROFESSIONALS, SUPPLIERS, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, AND MAKE NO WARRANTIES, REPRESENTATIONS, OR GUARANTEES IN CONNECTION WITH THIS WEBSITE, THE SERVICES OFFERED ON OR THROUGH THIS WEBSITE, ANY DATA, MATERIALS, SUBMITTED CONTENT, RELATING TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY OR COMPLETENESS OF ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THIS WEBSITE, INCLUDING WITHOUT LIMITATION THE MATERIALS, DATA AND SUBMITTED CONTENT OF OTHER USERS OF THIS SITE OR OTHER THIRD PARTIES. UNLESS OTHERWISE EXPLICITLY STATED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS WEBSITE, THE SERVICES OFFERED ON OR THROUGH THIS WEBSITE, DATA, MATERIALS, SUBMITTED CONTENT, AND ANY INFORMATION OR MATERIAL CONTAINED OR PRESENTED ON THIS WEBSITE IS PROVIDED TO YOU ON AN “AS IS,” “AS AVAILABLE” AND “WHEREIS” BASIS WITH NO WARRANTY OF IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD-PARTY RIGHTS. SELECTIALL DOES NOT PROVIDE ANY WARRANTIES AGAINST ERRORS, MISTAKES, OR INACCURACIES OF DATA, CONTENT, INFORMATION, MATERIALS, SUBSTANCE OF THE WEBSITE OR SUBMITTED CONTENT, ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE WEBSITE BY ANY THIRD PARTY, ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITE, ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY OR SERVICE USER OR SERVICE PROVIDER, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY DATA, CONTENT, INFORMATION, MATERIALS, SUBSTANCE OF THE WEBSITE OR SUBMITTED CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE WEBSITE. SELECTIALL DOES NOT ENDORSE, WARRANT, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE WEBSITE OR ANY HYPERLINKED SITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISEMENT. SELECTIALL WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY PARTY, INCLUDING THIRD PARTY SERVICE PROFESSIONALS OF PRODUCTS OR SERVICES. AS WITH THE USE OF ANY PRODUCT OR SERVICE, AND THE PUBLISHING OR POSTING OF ANY MATERIAL THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p><br>

      <h4><b>O. Limitations of Liability</b></h4><br>
      <p><ol type="1"><li>IN NO EVENT SHALL SELECTIALL, OR ITS RESPECTIVE OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, SUCCESSORS, ASSIGNS, SUBSIDIARIES, AFFILIATES, SERVICE PROFESSIONALS, SUPPLIERS, ATTORNEYS OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, CONSEQUENTIAL OR EXEMPLARY DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF BUSINESS, REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE) WHATSOEVER RESULTING FROM ANY:
        <ol type="A">
          <li> ACCESS TO OR USE OF THE WEBSITE OR ANY SERVICES OFFERED BY ANY SERVICE PROFESSIONALS VIA THE WEBSITE, INCLUDING SERVICES PROVIDED PURSUANT TO AN AGREEMENT FORMED INDEPENDENTLY OF THE WEBSITE, WHETHER OR NOT AN AGREEMENT FOR SERVICE FORMED VIA THE WEBSITE IS IN EFFECT</li>
          <li> ERRORS, MISTAKES, OR INACCURACIES OF DATA, MARKS, CONTENT, INFORMATION, MATERIALS OR SUBSTANCE OF THE WEBSITE OR SUBMITTED CONTENT</li>
          <li> ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN</li>
          <li> ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE WEBSITE BY ANY THIRD PARTY</li>
          <li> ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WEBSITE</li>
          <li> ANY ERRORS OR OMISSIONS IN ANY DATA, CONTENT, INFORMATION, MATERIALS OR SUBSTANCE OF THE WEBSITE OR SUBMITTED CONTENT</li>
          <li> ANY FAILED NEGOTIATIONS FOR A SERVICE, ANY DISPUTES THAT ARISE DURING OR AFTER THE NEGOTIATION OF A SERVICE OR THE FORMATION OF A CONTRACT FOR A SERVICE, OR ANY OTHER DISPUTE THAT ARISES BETWEEN USERS OF THE WEBSITE</li>
          <li> ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY OR SERVICE USER OR SERVICE PROFESSIONAL</li>
          <li> ANY USE OF ANY DATA, MARKS, CONTENT, INFORMATION, MATERIALS OR SUBSTANCE OF THE WEBSITE OR SUBMITTED CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE ON OR THROUGH THE WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT SELECTIALL IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</li>
        </ol></li><br>
          <li>IN NO EVENT SHALL THE TOTAL, AGGREGATE LIABILITY OF SELECTIALL, OR ANY OF THE ABOVE-REFERENCED RESPECTIVE PARTIES, ARISING FROM OR RELATING TO THE WEBSITE, AND/OR SUBMITTED CONTENT EXCEED THE TOTAL AMOUNT OF FEES ACTUALLY PAID TO SELECTIALL BY YOU HEREUNDER.
          YOU HEREBY ACKNOWLEDGE AND AGREE THAT SELECTIALL SHALL NOT BE LIABLE FOR SUBMITTED CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY OR SERVICE USER OR SERVICE PROVIDER AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. YOU FURTHER ACKNOWLEDGE AND AGREE THAT SELECTIALL SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, CONSEQUENTIAL OR EXEMPLARY DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF BUSINESS, REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE) WHATSOEVER RESULTING FROM OR RELATING TO ANY CONTRACT BETWEEN WEBSITE USERS ENTERED INTO INDEPENDENTLY OF THE WEBSITE.</li></ol>
          THE WEBSITE MAY CONTAIN LINKS TO THIRD-PARTY WEBSITES THAT ARE NOT OWNED OR CONTROLLED BY SELECTIALL. SELECTIALL DOES NOT HAVE ANY CONTROL OVER, AND ASSUMES NO RESPONSIBILITY FOR, THE CONTENT, PRIVACY POLICIES, OR PRACTICES OF ANY THIRD-PARTY WEBSITES. IN ADDITION, SELECTIALL WILL NOT AND CANNOT CENSOR OR EDIT THE CONTENT OF ANY THIRD-PARTY SITE. BY USING THE WEBSITE, YOU EXPRESSLY RELIEVE SELECTIALL FROM ANY AND ALL LIABILITY ARISING FROM YOUR USE OF ANY THIRDPARTY WEBSITE. ACCORDINGLY, PLEASE BE ADVISED TO READ THE TERMS AND CONDITIONS AND PRIVACY POLICY OF EACH THIRD-PARTY WEBSITE THAT YOU VISIT, INCLUDING THOSE DIRECTED BY THE LINKS CONTAINED ON THE WEBSITE.</p><br>

      <h4><b>P. FORCE MAJEURE</b></h4><br>
      <p>Neither Selectiall nor you shall be liable to the other for any delay or failure in performance under the Terms of Use, other than payment obligations, arising out of a cause beyond its control and without its fault or negligence. Such causes may include, but are not limited to fires, floods, earthquakes, strikes, unavailability of necessary utilities, blackouts, acts of God, acts of declared or undeclared war, acts of regulatory agencies, or national disasters.</p>
      <h5><b>Indemnification and Release</b></h5>
      <p>YOU AGREE TO DEFEND, INDEMNIFY AND HOLD HARMLESS SELECTIALL, AND ITS OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, SUCCESSORS, ASSIGNS, SUBSIDIARIES, AFFILIATES, SERVICE PROFESSIONALS, SUPPLIERS, AND AGENTS, FROM AND AGAINST ANY AND ALL CLAIMS, DAMAGES, OBLIGATIONS, LOSSES, LIABILITIES, COSTS OR DEBT, AND EXPENSES (INCLUDING BUT NOT LIMITED TO ATTORNEYS’ FEES) ARISING FROM YOUR USE OF, ACCESS TO, AND PARTICIPATION IN THE WEBSITE; YOUR VIOLATION OF ANY PROVISION OF THE TERMS OF USE, INCLUDING THE PRIVACY POLICY; YOUR VIOLATION OF ANY THIRD-PARTY RIGHT, INCLUDING WITHOUT LIMITATION ANY COPYRIGHT, PROPERTY, PROPRIETARY, INTELLECTUAL PROPERTY, OR PRIVACY RIGHT; OR ANY CLAIM THAT YOUR SUBMITTED CONTENT CAUSED DAMAGE TO A THIRD PARTY. THIS DEFENSE AND INDEMNIFICATION OBLIGATION WILL SURVIVE THESE TERMS OF SERVICE AND YOUR USE OF THE WEBSITE.<br><br>IF YOU HAVE A DISPUTE WITH ONE OR MORE WEBSITE USERS, YOU FOREVER RELEASE SELECTIALL (AND ITS OFFICERS, MANAGERS, MEMBERS, DIRECTORS, EMPLOYEES, SUCCESSORS, ASSIGNS, SUBSIDIARIES, AFFILIATES, SERVICE PROFESSIONALS, SUPPLIERS, AGENTS, SUBSIDIARIES, AND EMPLOYEES) FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES (ACTUAL AND CONSEQUENTIAL) OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH YOUR USE OF THE WEBSITE AND/OR ANY SUBMITTED CONTENT.<br><br>THE TERMS OF USE, AND ANY RIGHTS AND LICENSES GRANTED HEREUNDER, MAY NOT BE TRANSFERRED OR ASSIGNED BY YOU, BUT MAY BE ASSIGNED BY SELECTIALL WITHOUT RESTRICTION.</p><br>

      <h4><b>Q. No Third-party Beneficiaries</b></h4><br>
      <p>You agree that, except as otherwise expressly provided in the Terms of Use, there shall be no third-party beneficiaries to the Terms of Use.</p><br>

      <h4><b>R. Notice</b></h4>
      <p>You agree that Selectiall may provide you with notices, including those regarding changes to the Terms of Use, by email, regular mail, or postings on the Website.</p><br>

      <h4><b>S. General Information</b></h4><br>
      <h5><b>1. ENTIRE TERMS OF USE</b></h5>
      <p>The Terms of Use, together with the Privacy Policy and any other legal notices or Additional Policies published by Selectiall on the Website, shall constitute the entire agreement between you and Selectiall concerning the Website. If any provision of the Terms of Use is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of the Terms of Use, which shall remain in full force and effect.<br><br>No waiver of any provision of this these Terms of Use shall be deemed a further or continuing waiver of such term or any other term, and Selectiall’s failure to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
      <h5><b>2. STATUTE OF LIMITATIONS</b></h5>
      <p>You agree that any cause of action arising out of or related to the Website must commence within one year after the cause of action accrues. Otherwise, such cause of action is permanently barred.</p>
      <h5><b>3. SECTION HEADINGS</b></h5>
      <p>The section headings in the Terms of Use are for convenience only and have no legal or contractual effect.<br>© 2018 Onicorn Selectiall Services Private Limited. All Rights Reserved</p>

</div>

<?php include 'includes/footer.php' ?>
</body>
</html>
